language: c++
sudo: false

compiler:
    - clang
    - gcc

addons:
  apt:
    packages:
    - libncurses5-dev
    - build-essential
    - automake
    - autoconf

script: ./autogen.sh && make distcheck
